import { StyleSheet } from "react-native";


const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f9f9f9",
    },
    header: {
        backgroundColor: "#4252e5",
        flexDirection: "row",
        alignItems: "center",
        paddingVertical: 16,
        paddingHorizontal: 20,
    },
    backButton: {
        marginRight: 16,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "bold",
        color: "white",
    },
    content: {
        flex: 1,
        padding: 20,
    },
    assignmentHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    courseTag: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 6,
    },
    courseTagText: {
        color: "white",
        fontWeight: "600",
        fontSize: 14,
    },
    dueDate: {
        fontSize: 14,
        color: "#ff5252",
        fontWeight: "500",
    },
    assignmentTitle: {
        fontSize: 22,
        fontWeight: "bold",
        marginBottom: 8,
    },
    assignmentDescription: {
        fontSize: 15,
        color: "#555",
        lineHeight: 22,
        marginBottom: 20,
    },
    section: {
        marginBottom: 24,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 12,
    },
    requirementsList: {
        backgroundColor: "white",
        borderRadius: 12,
        padding: 16,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    requirementItem: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 10,
    },
    requirementText: {
        marginLeft: 10,
        fontSize: 15,
        color: "#333",
    },
    rubricContainer: {
        backgroundColor: "white",
        borderRadius: 12,
        overflow: "hidden",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    rubricHeader: {
        flexDirection: "row",
        backgroundColor: "#f0f0f0",
        paddingVertical: 12,
        paddingHorizontal: 16,
    },
    rubricCriteriaHeader: {
        flex: 1,
        fontWeight: "bold",
        fontSize: 15,
    },
    rubricPointsHeader: {
        width: 60,
        textAlign: "right",
        fontWeight: "bold",
        fontSize: 15,
    },
    rubricRow: {
        flexDirection: "row",
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    lastRubricRow: {
        borderBottomWidth: 0,
    },
    rubricCriteria: {
        flex: 1,
        fontSize: 15,
    },
    rubricPoints: {
        width: 60,
        textAlign: "right",
        fontSize: 15,
        fontWeight: "500",
    },
    rubricTotalRow: {
        flexDirection: "row",
        paddingVertical: 12,
        paddingHorizontal: 16,
        backgroundColor: "#f0f0f0",
        borderTopWidth: 1,
        borderTopColor: "#ddd",
    },
    rubricTotalLabel: {
        flex: 1,
        fontWeight: "bold",
        fontSize: 15,
    },
    rubricTotalPoints: {
        width: 60,
        textAlign: "right",
        fontWeight: "bold",
        fontSize: 15,
        color: "#5c51f3",
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 8,
    },
    notesInput: {
        backgroundColor: "white",
        borderRadius: 12,
        padding: 16,
        height: 120,
        textAlignVertical: "top",
        marginBottom: 20,
        fontSize: 15,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    attachmentsContainer: {
        backgroundColor: "white",
        borderRadius: 12,
        padding: 16,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    attachmentItem: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
    attachmentInfo: {
        flexDirection: "row",
        alignItems: "center",
        flex: 1,
    },
    attachmentDetails: {
        marginLeft: 12,
        flex: 1,
    },
    attachmentName: {
        fontSize: 15,
        fontWeight: "500",
    },
    attachmentSize: {
        fontSize: 13,
        color: "#777",
        marginTop: 2,
    },
    removeButton: {
        padding: 6,
    },
    addAttachmentButton: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        paddingVertical: 12,
        marginTop: 8,
    },
    addAttachmentText: {
        color: "#5c51f3",
        fontSize: 16,
        fontWeight: "600",
        marginLeft: 8,
    },
    submitButton: {
        backgroundColor: "#5c51f3",
        borderRadius: 12,
        paddingVertical: 16,
        alignItems: "center",
        marginTop: 20,
        marginBottom: 40,
    },
    submitButtonText: {
        color: "white",
        fontSize: 16,
        fontWeight: "bold",
    },
});

export default styles;